<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url(
        'auth',
        array(
            'action'     => 'index',
            'controller' => 'auth'
        )
    ));
    $form->prepare();
?>
 
<?php echo $this->form()->openTag($form);?>

    <ul class="signup">
        
        <h1 id="signup">User Login</h1>
        <?php echo '<li>'.$this->message.'</li>';?>
        <?php echo '<li>'.$this->formRow($form->get('username')).'</li>';?>
        <?php echo '<li>'.$this->formRow($form->get('password')).'</li>';?>
        <?php echo '<li>'.$this->formRow($form->get('submit')).'</li>';?>
    </ul>
<?php echo $this->form()->closeTag();?>

<?php 
$url = $this->url(
        'auth',
        array(
            'action'     => 'newuser',
            'controller' => 'auth'
        ));
?>
<p>Not a member <a href="<?php echo $url;?>">click here</a> and sign up, it's free and you can share your thoughts with us.</p>