<form method="POST" action="/login">
    <ul class="signup">
        <h1 id="signup">User Login</h1>
        <li>User Name: <input type="text"></li>
        <li>Password:  <input type="password"></li>
        <li>Captcha:  <input type="text" name="captcha[input]"></li>
        <li><img src="images/captcha/login/<?php echo $this->CaptchaID;?>.png" alt="captcha"></li>
        <li><input type="hidden" value="<?php echo $this->CaptchaID?>" name="captcha[id]" /></li>
        <li><input type="submit" value="Submit"></li>
    </ul>  
</form>
<p>Not a member <a href="/login/newuser">click here</a> and sign up, it's free and you can share your thought's with us.</p>