<?php
    $form = $this->form;

    //Remove default error messages.
    $this->formRow()->setRenderErrors(false);
    $form->setAttribute('action', $this->url(
        'auth',
        array(
            'action'     => 'newuser',
            'controller' => 'auth'
        )
    ));
    $form->prepare();
?>
 
<?php echo $this->form()->openTag($form);?>

    <ul class="signup">
        
        <h1 id="signup">User Sign up</h1>
        <?php echo '<li>'.$this->message.'</li>';?>
        <?php echo '<li>'.$this->formRow($form->get('username')).'</li>';?>
        <?php echo '<li>'.$this->formRow($form->get('email')).'</li>';?>
        <?php echo '<li>'.$this->formRow($form->get('password')).'</li>';?>
        <?php echo '<li>'.$this->formRow($form->get('captcha')).'</li>';?>
        <?php echo '<li>'.$this->formRow($form->get('submit')).'</li>';?>
    </ul>
<?php echo $this->form()->closeTag();?>