
<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url(
        'auth',
        array(
            'action'     => 'test',
            'controller' => 'auth'
        )
    ));
    $form->prepare();
?>
 
<?php echo $this->form()->openTag($form);?>

    <ul class="signup">
        
        <h1 id="signup">User Login</h1>
        <?php echo '<li>'.$this->formCollection($form).'</li>';?>
    </ul>
<?php echo $this->form()->closeTag();?>