<div class="right_col_section">
    <div id="welcome_title"></div><h1><?php echo ( isset($this->User_Name) ? $this->User_Name : "Friend" ); ?></h1>
  <p><img src="/css/templatemo_image_01.jpg" alt="church" />This is a <a href="http://www.templatemo.com" target="_parent">FREE CSS  template</a> provided by <a href="http://www.templatemo.com/page/1" target="_parent">templatemo.com</a> website. You may apply this website layout in your websites. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum egestas dapibus augue. Proin sed orci quis metus semper ultricies. </p>
  <p>Credit goes to <a href="http://www.photovaco.com" target="_blank">PhotoVaco.com</a> for photos.</p>
  <p>Nulla tincidunt, dui eget vehicula sodales, neque nulla hendrerit urna, vitae vehicula orci odio et dolor. Aenean quis mi. Donec orci risus.</p>
</div>
    <div class="cleaner_with_height">&nbsp;</div>
<div class="right_col_section">
    <div class="right_two_col">
            <h2>Worship Place  &amp; Time</h2>
        <img src="/css/templatemo_map.jpg" alt="map" />
        <h3>Place</h3>
      66, dui eget,<br />
        Mauris quis nulla, Nulla imperdiet, 00100
        <p></p>
        <h3>Time</h3>
        <p>March 25, 2048 Sunday (11:00 AM)</p>
    </div>

    <div class="right_cleaner_with_10px">&nbsp;</div>

    <div class="right_two_col">

        <h2>Education Programs</h2>
        <p>Mauris quis nulla sed ipsum pretium sagittis. Suspendisse feugiat. Ut sodales libero ut odio. Maecenas venenatis metus eu est. In sed risus ac felis varius bibendum. Nulla imperdiet congue metus.</p>
        <ul>
            <li><a href="#">Suspendisse feugiat</a></li>
          <li><a href="#">Maecenas venenatis metus</a></li>
          <li><a href="#">In sed risus ac feli</a></li>
          <li><a href="#">Vestibulum egestas dapibus augue</a></li>
          <li><a href="#">Aenean eget tortor eget</a></li>
        </ul>

        <a href="http://validator.w3.org/check?uri=referer"><img style="border:0;width:88px;height:31px" src="http://www.w3.org/Icons/valid-xhtml10" alt="Valid XHTML 1.0 Transitional" width="88" height="31" vspace="8" border="0" /></a>
        <a href="http://jigsaw.w3.org/css-validator/check/referer"><img style="border:0;width:88px;height:31px"  src="http://jigsaw.w3.org/css-validator/images/vcss-blue" alt="Valid CSS!" vspace="8" border="0" /></a>
    </div> 
    <div class="cleaner">&nbsp;</div>          
</div>